- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-wholedisk-bios-ipmi-direct-tinyipa-src
        - ironic-lib-partition-bios-ipmi-direct-tinyipa-src
        - ironic-lib-partition-bios-ipmi-iscsi-tinyipa-src
        - ironic-lib-wholedisk-bios-ipmi-iscsi-tinyipa-src
    gate:
      queue: ironic
      jobs:
        - ironic-lib-wholedisk-bios-ipmi-direct-tinyipa-src
        - ironic-lib-partition-bios-ipmi-direct-tinyipa-src
        - ironic-lib-partition-bios-ipmi-iscsi-tinyipa-src
        - ironic-lib-wholedisk-bios-ipmi-iscsi-tinyipa-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
