- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-uefi-ipmi-src
        - ironic-lib-bios-ipmi-src
        - ironic-lib-tox-codespell:
            voting: false
    gate:
      jobs:
        - ironic-lib-uefi-ipmi-src
        - ironic-lib-bios-ipmi-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
